name: Test OSS scan workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  periphery:
    permissions:
      contents: read
      id-token: write
    uses: periphery-pro/actions/.github/workflows/scan.yml@v1.0.0.beta.1
