name: Test

on:
  pull_request:
    branches: [main, demo-base]
  push:
    branches: [main, demo-base]
  workflow_dispatch:

permissions: {}

jobs:
  periphery:
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: periphery-pro/actions/.github/workflows/scan.yml@feat/job-summary
    with:
      post_comment: false
